[Fix Issue #4] Add "How to contribute" section to README
algoristas/dashboard pull request #9
Opened 2017-10-05 14:05 UTC by Gansito144

* Including some links

2017-10-05 14:33 UTC, rendon approved these changes
Thanks for adding this info, just a couple suggestions.

2017-10-05 14:33 UTC, rendon commented on README.md
> +Contribution is very welcome, you can review [current issues](https://github.com/algoristas/dashboard/issues) or request a new one by creating a new issue.
Pluralization: Contribution*s*

2017-10-05 14:33 UTC, rendon commented on README.md
> +* Made your changes and add them `git add <list of your files>`
Make?

2017-10-05 14:33 UTC, rendon commented on README.md
> +* Create a commit with an appropiate message `git commit` [guidelines](https://chris.beams.io/posts/git-commit/)
I think most people know they have to commit their changes, I would just say something like: _Try to follow the guidelines at <the link> for your commits_.

2017-10-06 00:59 UTC, rendon requested changes

2017-10-06 00:59 UTC, rendon commented on README.md
> +Contribution are welcome, you can review [current issues](https://github.com/algoristas/dashboard/issues) or create a new one.
You missed the *s* in Contribution :)

2017-10-06 00:59 UTC, rendon commented on README.md
> +Once you selected issue to work on, follow these steps to submit your changesi, then create a pull request.
changesi?

2017-10-06 01:07 UTC, Gansito144 commented on README.md
> +Contribution are welcome, you can review [current issues](https://github.com/algoristas/dashboard/issues) or create a new one.
Damn it!

2017-10-06 01:08 UTC, Gansito144 commented on README.md
> +Once you selected issue to work on, follow these steps to submit your changesi, then create a pull request.
I blame vim for this :p

2017-10-06 01:12 UTC, rendon approved these changes
Do it!

2017-10-06 01:18 UTC, merged